// This file is generated by .build/generate-annotation-types.js — do not edit by hand.
// Source: https://editions.sub.uni-goettingen.de/annotationapi-specs/0.1.0/schema.json (version 0.1.0)

declare global {
  /**
   * Annotation
   * @description An Annotation as it is returned by the API.
   */
  interface Annotation {
    /**
     * Type
     * @default Annotation
     */
    type?: string | string[]
    /** Target */
    target: SpecificResource | string | (SpecificResource | string)[]
    /** Body */
    body?: SpecificResource | EmbeddedTextualBody | string | (SpecificResource | EmbeddedTextualBody | string)[] | null
    /**
     * JSON-LD Context(s)
     * Format: uri
     * @default ["http://www.w3.org/ns/anno.jsonld","https://editions.sub.uni-goettingen.de/ns/textapi.jsonld"]
     */
    '@context'?: string | string[]
    /**
     * Id
     * Format: uri
     */
    id: string
    /** Created */
    created: string
    /** Modified */
    modified: string
    /** Via */
    via?: string | null
  }
  /**
   * Collection
   * @description An Annotation Collection.
   */
  interface AnnotationCollection {
    /**
     * @Context
     * Format: uri
     * @default ["http://www.w3.org/ns/anno.jsonld","http://www.w3.org/ns/ldp.jsonld"]
     */
    '@context'?: string[]
    /**
     * Id
     * Format: uri
     */
    id: string
    /**
     * Type
     * @default ["AnnotationCollection","BasicContainer"]
     */
    type?: string | string[]
    /** Modified */
    modified: string
    /** Created */
    created: string
    /**
     * Total
     * @default 0
     */
    total?: number
    /** First */
    first?: string | EmbeddedAnnotationPage | null
    /**
     * Last
     * Format: uri
     */
    last?: string | null
  }
  /**
   * Page
   * @description An Annotation Collection’s Page.
   */
  interface AnnotationPage {
    /**
     * Id
     * Format: uri
     */
    id: string
    /**
     * Type
     * @default AnnotationPage
     */
    type?: string | string[]
    /** Items */
    items: EmbeddedAnnotation[] | string[]
    /**
     * Next
     * Format: uri
     */
    next?: string | null
    /**
     * Prev
     * Format: uri
     */
    prev?: string | null
    /**
     * Startindex
     * @default 0
     */
    startIndex?: number
    /**
     * @Context
     * Format: uri
     * @default http://www.w3.org/ns/anno.jsonld
     */
    '@context'?: string | string[]
    /** Partof */
    partOf: EmbeddedAnnotationCollection | string
  }
  /**
   * Source
   * @description The source resource for a SpecificResource.
   */
  interface AnnotationTargetSource {
    /**
     * Id
     * Format: uri
     */
    id: string
    /**
     * Collection
     * Format: uri
     */
    collection?: string | null
    /**
     * Manifest
     * Format: uri
     */
    manifest?: string | null
    /**
     * Item
     * Format: uri
     */
    item?: string | null
  }
  /**
   * CssSelector
   * @description The type of the CSS Selector resource.
   */
  interface CssSelector {
    refinedBy?: Selector | null
    /**
     * Type
     * @default CssSelector
     */
    type?: string
    /** Value */
    value: string
  }
  /**
   * EmbeddedAnnotation
   * @description An Annotation object embedded in a Page.
   */
  interface EmbeddedAnnotation {
    /**
     * Type
     * @default Annotation
     */
    type?: string | string[]
    /** Target */
    target: SpecificResource | string | (SpecificResource | string)[]
    /** Body */
    body?: SpecificResource | EmbeddedTextualBody | string | (SpecificResource | EmbeddedTextualBody | string)[] | null
    /**
     * Id
     * Format: uri
     */
    id: string
    /** Via */
    via?: string | null
    /** Created */
    created: string
    /** Modified */
    modified: string
  }
  /**
   * EmbeddedCollection
   * @description An Annotation Collection embedded in a page document.
   */
  interface EmbeddedAnnotationCollection {
    /**
     * @Context
     * Format: uri
     * @default http://www.w3.org/ns/ldp.jsonld
     */
    '@context'?: string | string[]
    /**
     * Id
     * Format: uri
     */
    id: string
    /** Modified */
    modified: string
    /** Created */
    created: string
    /** Total */
    total: number
    /**
     * First
     * Format: uri
     */
    first: string
    /**
     * Last
     * Format: uri
     */
    last: string
  }
  /**
   * EmbeddedPage
   * @description An Annotation Collection’s Page embedded in a collection document.
   */
  interface EmbeddedAnnotationPage {
    /**
     * Id
     * Format: uri
     */
    id: string
    /**
     * Type
     * @default AnnotationPage
     */
    type?: string | string[]
    /** Items */
    items: EmbeddedAnnotation[] | string[]
    /**
     * Next
     * Format: uri
     */
    next?: string | null
    /**
     * Prev
     * Format: uri
     */
    prev?: string | null
    /**
     * Startindex
     * @default 0
     */
    startIndex?: number
  }
  /**
   * EmbeddedTextualBody
   * @description The embedded textual body model.
   */
  interface EmbeddedTextualBody {
    /** Format */
    format?: string | string[] | null
    /** Language */
    language?: string | string[] | null
    /** Processinglanguage */
    processingLanguage?: string | null
    /** Textdirection */
    textDirection?: 'ltr' | 'rtl' | 'auto' | null
    /** AnnotationType */
    annotationType?: string | null
    /** Value */
    value: string
  }
  /**
   * FragmentSelector
   * @description A resource which describes the Segment through the use of the fragment component
   * of an IRI.
   */
  interface FragmentSelector {
    refinedBy?: Selector | null
    /**
     * Type
     * @default FragmentSelector
     */
    type?: string
    /** Value */
    value: string
    /** Conformsto */
    conformsTo?: string | null
  }
  /**
   * HttpRequestState
   * @description The HttpRequestState resource maintains a copy of the headers to be replayed when
   * obtaining the representation.
   */
  interface HttpRequestState {
    /** Refinedby */
    refinedBy?: State | Selector | (State | Selector)[] | null
    /**
     * Type
     * @default HttpRequestState
     * @constant
     */
    type?: 'HttpRequestState'
    /** Value */
    value: string
  }
  /** Selector */
  type Selector = FragmentSelector | CssSelector
  /**
   * SpecificResource
   * @description The class for Specific Resources.
   */
  interface SpecificResource {
    /**
     * Id
     * Format: uri
     */
    id?: string | null
    /**
     * Type
     * @default SpecificResource
     * @constant
     */
    type?: 'SpecificResource'
    /** Source */
    source: string | AnnotationTargetSource
    /** Purpose */
    purpose?: string | string[] | null
    /** Selector */
    selector?: Selector | string | (Selector | string)[] | null
    /** State */
    state?: State | State[] | null
  }
  /** State */
  type State = HttpRequestState | TimeState
  /**
   * TimeState
   * @description A Time State resource records the time at which the resource is appropriate for
   * the Annotation, typically the time that the Annotation was created and/or a link to
   * a persistent copy of the current version.
   */
  interface TimeState {
    /** Refinedby */
    refinedBy?: State | Selector | (State | Selector)[] | null
    /**
     * Type
     * @default TimeState
     * @constant
     */
    type?: 'TimeState'
    /** Sourcedate */
    sourceDate?: string | null
    /** Sourcedatestart */
    sourceDateStart?: string | null
    /** Sourcedateend */
    sourceDateEnd?: string | null
    /** Cached */
    cached?: unknown
  }
}

export {}
